### ISSUE TITLE
USER STORY: Refactoring components and pages for Material UI

### ISSUE THREAD

**Issue by NahomAlemu** [SeattleColleges/nsc-events-nextjs#147]
As a developer, I want to refactor the files to follow Material UI style guidelines,
So that the page and component files have a consistent and modern user interface aligning with Material UI design principles.

Issues:
- [x] [create-event/page.tsx](https://github.com/SeattleColleges/nsc-events-nextjs/issues/148)
- [x] InputFields.tsx
- [x] [sign-up](https://github.com/SeattleColleges/nsc-events-nextjs/issues/154)
- [x] [sign-in page](https://github.com/SeattleColleges/nsc-events-nextjs/issues/162)
- [x] [Forgot-password page](https://github.com/SeattleColleges/nsc-events-nextjs/issues/176)
