### ISSUE TITLE
USER STORY: UI updates

### ISSUE THREAD

**Issue by NahomAlemu** [SeattleColleges/nsc-events-nextjs#196]
As a developer, I want to update the styling of input fields and buttons across sign-in, sign-up, and forgot password pages. Implement consistent text field and label colors (white background with black text) and increase the label font size for better readability. Unified button color scheme to a consistent blue across all forms. Centralized input field styles with `textFieldStyle` for easier maintenance and implementation across components.

Tasks:

- [x] [Make the background color of all of the pages a solid plain color](https://github.com/SeattleColleges/nsc-events-nextjs/issues/197)
- [x] [Uniform button colors](https://github.com/SeattleColleges/nsc-events-nextjs/issues/198) 
- [x] [Standardized Input Fields and Button Styles Across Auth Pages](https://github.com/SeattleColleges/nsc-events-nextjs/issues/199)
