### ISSUE TITLE
USER STORY: Archived Events Page

### ISSUE THREAD

**Issue by intisarosman1** [SeattleColleges/nsc-events-nextjs#296]
As a developer, I will want to create a placeholder Archived Events page and the necessary buttons to route to the page from the admin and creator pages.

- [x] [Create placeholder Archived Events page](https://github.com/SeattleColleges/nsc-events-nextjs/issues/297)
- [x] [Create View Archived Events button on admin page](https://github.com/SeattleColleges/nsc-events-nextjs/issues/297)
- [x] [Create View Archived Events button on creator page](https://github.com/SeattleColleges/nsc-events-nextjs/issues/297)
