### ISSUE TITLE
Feature: Event Detail Page Add Document Field to More Details

### ISSUE THREAD

**Issue by RMaffei** [SeattleColleges/nsc-events-nextjs#555]
For this feature addition, I want to add a document field to the More Details dialog to display information for users, creators, and admins.

### 1. Feature Name:
<Feature: Event Detail Page Add Document Field to More Details>

### 2. Details:

- Feature: Add new document field to 'More Details' dialog
- Make changes in component 'ViewMoreDetailsDialog'
- End result: Should display a document field that shows relevant information to users.

### 3. Roles:

- Admin, Creator, User should all see details after implementation. 

### Tasks:
- [x] Update 'ViewMoreDetailsDialog' component to include doc field
- [x] Ensure it is included in all connected arrays 
- [x] Ensure conditional rendering for relevant user roles
- [x] Test the component across user roles to ensure it is display correctly

**Comment by BradleyCharles** [comment]
Student is not participating this term. I am closing this so it can be completed by someone else
